#!/bin/bash

css = $(git diff --cached --name-only | grep -E '.css' | xargs git diff --cached --diff-filter=ACM -U0 --)

if [[ css ]]; then

            echo ""
            echo "--> you checked in css files. lets comb them..."
            echo ""

            # check if csscomb is installed

            if hash csscomb 2>/dev/null; then

                echo -e "\033[1;32m--> found csscomb\033[0m"
                

                # TODO: check for csscomb update once a week
                
                # check if configfile exists

                if [ ! -f ./.csscomb.json ]; then
                    echo "--> no config file, using defaults"
                else
                    echo -e "\033[1;32m--> found .csscomb.json\033[0m"

                fi

                echo ""

                # Necessary check for initial commit
                against="2dbc9309507e421dc3f468a6ec38905c5362a2e7"
                git rev-parse --verify HEAD >/dev/null 2>&1 && against="HEAD"
                EXITCODE=0

                # (A)dded (C)opied or (M)odified
                # encapsulate the loop in {} http://stackoverflow.com/a/13665483/3019532
                git diff-index --cached --full-index --diff-filter=ACM $against | \
                {
                    while read -r line; do
                      FILE_PATH="$(echo ${line} |cut -d' ' -f6-)"
                      EXTENSION="${FILE_PATH##*.}"
                      # EXTENSION=${EXTENSION,,} # Convert to lowercase
                      REGEX=""
                     
                      # Select discouraged words based on extension

                      if [ "${EXTENSION}" = "css" ]; then
                        echo "--> staged css file: " $FILE_PATH
                        echo "--> combing..."
                        csscomb $FILE_PATH
                        echo "--> adding combed file"
                        git add $FILE_PATH
                        echo "--> done"
                        echo ""
                      fi
                    done
                }
                

            else
                echo -e "\033[0;31m--> Oh noes, CSS Comb is not installed. Do:"
                echo "--> npm install csscomb -g"
                echo -e "\033[0m"
                echo "--> (you need to change and stage a css file again to see it work on the next commit...)"
                echo ""
            fi
fi


# Necessary check for initial commit
against="2dbc9309507e421dc3f468a6ec38905c5362a2e7"
git rev-parse --verify HEAD >/dev/null 2>&1 && against="HEAD"
EXITCODE=0

exit 0
